#!/usr/bin/env python3
"""Generate the portfolio sections of README.md from data/portfolio.json + GitHub.

Two sources feed the generated blocks:

  * Curated   – data/portfolio.json: product families (one entry may group
                several repositories, platforms or services), the archive text
                for public repositories, allowlisted private archive entries and
                the list of repositories that must never appear.
  * Automatic – public repositories owned by OWNER from the public GitHub REST
                API (pagination followed). Repositories claimed by a product
                family are consumed by that family; the rest land in the
                collapsed archive. Forks, disabled/empty repositories, the
                profile repository itself, `profile-hide` topics and every name
                in `profile_excluded_repositories` are skipped.

README.md holds two marker regions that are replaced wholesale:

  <!-- PORTFOLIO:START --> … <!-- PORTFOLIO:END -->   flagships, ecosystem, collaborations
  <!-- ARCHIVE:START -->   … <!-- ARCHIVE:END -->     complete collapsed archive

The proof-strip SVGs (assets/v5/proof-strip-*.svg) are rendered from
data/footprint.json so the numbers shown are exactly the measured ones.

Guarantees: deterministic output for the same input; idempotent (a second run
changes nothing); only the marker regions of README.md are touched; Markdown
is escaped; the only github.com links ever emitted point at listed public
repositories of OWNER; an excluded repository can never reappear; an empty or
failing API response never wipes the existing blocks; the token (if any) is
read from GITHUB_TOKEN and never printed. Standard library only.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Callable, Iterable

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render_assets import asset_path, render_proof_strip  # noqa: E402

OWNER = "Salihefendihsa"
PROFILE_REPO = OWNER  # the profile README repository has the same name as the owner
API_BASE = "https://api.github.com"
PER_PAGE = 100
TIMEOUT_SECONDS = 20
MAX_PAGES = 20

PORTFOLIO_START = "<!-- PORTFOLIO:START -->"
PORTFOLIO_END = "<!-- PORTFOLIO:END -->"
ARCHIVE_START = "<!-- ARCHIVE:START -->"
ARCHIVE_END = "<!-- ARCHIVE:END -->"
GENERATED_NOTE = "<!-- Generated by scripts/generate_portfolio.py from data/portfolio.json + the public GitHub API. Do not edit by hand. -->"

DEFAULT_PORTFOLIO = os.path.join("data", "portfolio.json")
DEFAULT_FOOTPRINT = os.path.join("data", "footprint.json")
DEFAULT_OUT_PORTFOLIO = os.path.join("generated", "portfolio.md")
DEFAULT_OUT_ARCHIVE = os.path.join("generated", "project-archive.md")

ASSET_PREFIX = "assets/v5"
MAX_FLAGSHIPS = 3
MAX_BUILT = 4  # flagship bullet budget keeps the story within a few desktop screens

HIDE_TOPIC = "profile-hide"
COURSEWORK_TOPICS = {"academic", "coursework", "lab", "university"}
GROUP_TOOLS = "Tools & Research"
GROUP_COURSEWORK = "University Coursework"
GROUP_EARLIER = "Earlier Work"
DEFAULT_ARCHIVE_GROUPS = (GROUP_TOOLS, GROUP_COURSEWORK, GROUP_EARLIER)

PRODUCT_REQUIRED = ("product_id", "display_name", "tagline", "summary", "role", "status", "access",
                    "category", "repository_sources", "stack", "featured_tier", "sort_order")
PRODUCT_ALLOWED = set(PRODUCT_REQUIRED) | {
    "problem", "built", "surfaces", "status_note", "public_links", "visual", "publish_name",
    "publish_repository_links", "collaboration",
}
SOURCE_KINDS = ("public", "private", "collaboration")
OVERRIDE_ALLOWED = {"display_name", "summary", "stack", "group"}
PRIVATE_ARCHIVE_ALLOWED = {"display_name", "summary", "stack", "group", "access"}
PUBLIC_REPO_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")


class PortfolioError(Exception):
    """Raised for any condition under which README.md must not be modified."""


# --------------------------------------------------------------------------- model

@dataclass
class Product:
    product_id: str
    name: str
    tagline: str
    summary: str
    role: str
    status: str
    access: str
    category: str
    stack: list[str]
    tier: int
    sort_order: int
    problem: str = ""
    built: list[str] = field(default_factory=list)
    surfaces: list[str] = field(default_factory=list)
    status_note: str = ""
    visual: str = ""
    public_repos: list[str] = field(default_factory=list)   # "owner/name", verified public
    public_links: list[dict] = field(default_factory=list)
    publish_repository_links: bool = False
    collaboration: dict | None = None

    @property
    def is_collaboration(self) -> bool:
        return self.collaboration is not None

    @property
    def repo_urls(self) -> list[tuple[str, str]]:
        if not self.publish_repository_links:
            return []
        return [(full.split("/", 1)[1], f"https://github.com/{full}") for full in self.public_repos]


@dataclass
class ArchiveEntry:
    name: str
    summary: str
    stack: str
    group: str
    access: str
    url: str = ""


# --------------------------------------------------------------------------- fetch

def fetch_public_repos(owner: str = OWNER, opener: Callable[..., Any] | None = None) -> list[dict]:
    """Fetch all public repositories owned by `owner`, following pagination."""
    opener = opener or urllib.request.urlopen
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    repos: list[dict] = []
    for page in range(1, MAX_PAGES + 1):
        url = f"{API_BASE}/users/{owner}/repos?type=owner&per_page={PER_PAGE}&page={page}&sort=full_name"
        req = urllib.request.Request(url, headers={
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": f"{owner}-portfolio-generator",
        })
        if token:
            req.add_header("Authorization", f"Bearer {token}")
        try:
            with opener(req, timeout=TIMEOUT_SECONDS) as resp:
                status = getattr(resp, "status", 200)
                if status != 200:
                    raise PortfolioError(f"GitHub API returned HTTP {status} for page {page}")
                batch = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            raise PortfolioError(f"GitHub API HTTP error {exc.code} on page {page}") from None
        except (urllib.error.URLError, TimeoutError, OSError, ValueError) as exc:
            raise PortfolioError(f"GitHub API request failed on page {page}: {exc.__class__.__name__}") from None
        if not isinstance(batch, list):
            raise PortfolioError("Unexpected API payload (expected a list)")
        repos.extend(batch)
        if len(batch) < PER_PAGE:
            break
    return repos


# --------------------------------------------------------------------------- helpers

_MD_SPECIAL = re.compile(r"([\\`*_\[\]|<>~#])")


def escape_md(text: Any) -> str:
    """Escape Markdown/HTML-significant characters and collapse whitespace (table safe)."""
    text = " ".join(str(text or "").split())
    return _MD_SPECIAL.sub(r"\\\1", text)


def cell(text: Any) -> str:
    out = escape_md(text)
    return out or "—"


def safe_http_url(url: str) -> str:
    """Return the URL if it is a plain absolute http(s) URL, otherwise ''."""
    url = (url or "").strip()
    if not url or any(ch.isspace() for ch in url) or any(ch in url for ch in "()<>\"'`"):
        return ""
    try:
        parts = urllib.parse.urlsplit(url)
    except ValueError:
        return ""
    if parts.scheme not in ("http", "https") or not parts.netloc or "." not in parts.netloc:
        return ""
    return url


def is_github_url(url: str) -> bool:
    try:
        host = (urllib.parse.urlsplit(url).hostname or "").lower()
    except ValueError:
        return False
    return host == "github.com" or host.endswith(".github.com")


def _topics(repo: dict) -> set[str]:
    return {str(t).lower() for t in (repo.get("topics") or [])}


def _lower_set(values: Iterable[str]) -> set[str]:
    return {str(v).strip().lower() for v in values if str(v).strip()}


# --------------------------------------------------------------------------- public repositories

def excluded_names(portfolio: dict) -> set[str]:
    return _lower_set(portfolio.get("profile_excluded_repositories") or [])


def is_listed(repo: dict, portfolio: dict, owner: str = OWNER, profile_repo: str = PROFILE_REPO) -> bool:
    """Whether a repository from the API may appear anywhere in the README."""
    name = str(repo.get("name", ""))
    if repo.get("private") or repo.get("visibility", "public") != "public":
        return False
    if (repo.get("owner") or {}).get("login", "").lower() != owner.lower():
        return False
    if repo.get("fork") or repo.get("disabled"):
        return False
    if name.lower() == profile_repo.lower():
        return False
    if name.lower() in excluded_names(portfolio):
        return False
    if HIDE_TOPIC in _topics(repo):
        return False
    if int(repo.get("size") or 0) == 0 and not repo.get("language"):
        return False  # empty repository
    return True


def repo_url(owner: str, name: str) -> str:
    return f"https://github.com/{owner}/{name}"


def archive_entry_from_repo(repo: dict, overrides: dict, groups: tuple[str, ...], owner: str = OWNER) -> ArchiveEntry:
    name = str(repo.get("name", ""))
    override = overrides.get(name) or {}
    url = repo_url(owner, name)
    if safe_http_url(str(repo.get("html_url", ""))) != url:
        raise PortfolioError(f"unexpected repository URL for {name!r}; refusing to link it")
    topics = _topics(repo)
    if override.get("group"):
        group = override["group"]
    elif repo.get("archived") or "archived" in topics:
        group = GROUP_EARLIER
    elif topics & COURSEWORK_TOPICS:
        group = GROUP_COURSEWORK
    else:
        group = GROUP_TOOLS
    if group not in groups:
        raise PortfolioError(f"archive override for {name!r} uses unknown group {group!r}")
    summary = override.get("summary") or " ".join(str(repo.get("description") or "").split())
    if not summary:
        lang = repo.get("language") or ""
        summary = f"{lang} repository; description not published yet." if lang else "Description not published yet."
    return ArchiveEntry(
        name=override.get("display_name") or name,
        summary=summary,
        stack=override.get("stack") or (repo.get("language") or ""),
        group=group,
        access="Public",
        url=url,
    )


# --------------------------------------------------------------------------- portfolio file

def load_portfolio(path: str) -> dict:
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    validate_portfolio(data)
    return data


def archive_groups(data: dict) -> tuple[str, ...]:
    groups = tuple(str(g) for g in (data.get("archive_groups") or DEFAULT_ARCHIVE_GROUPS))
    return groups if GROUP_EARLIER in groups else groups + (GROUP_EARLIER,)


def validate_portfolio(data: Any) -> None:
    if not isinstance(data, dict) or not isinstance(data.get("products"), list):
        raise PortfolioError("portfolio must be an object with a 'products' list")
    excluded = excluded_names(data)
    groups = archive_groups(data)
    ids: set[str] = set()
    names: set[str] = set()
    flagships = 0
    for i, p in enumerate(data["products"]):
        if not isinstance(p, dict):
            raise PortfolioError(f"product {i} is not an object")
        unknown = set(p) - PRODUCT_ALLOWED
        if unknown:
            raise PortfolioError(f"product {i} has disallowed field(s): {sorted(unknown)}")
        for key in PRODUCT_REQUIRED:
            if key not in p:
                raise PortfolioError(f"product {i} is missing {key!r}")
        for key in ("product_id", "display_name", "tagline", "summary", "role", "status", "access", "category"):
            if not str(p[key]).strip():
                raise PortfolioError(f"product {i} has an empty {key!r}")
        pid = str(p["product_id"])
        if pid in ids:
            raise PortfolioError(f"duplicate product_id {pid!r}")
        ids.add(pid)
        key = " ".join(str(p["display_name"]).lower().split())
        if key in names:
            raise PortfolioError(f"duplicate product name {p['display_name']!r}")
        names.add(key)
        if p["featured_tier"] not in (1, 2, 3):
            raise PortfolioError(f"product {pid!r} has an invalid featured_tier")
        if p["featured_tier"] == 1:
            flagships += 1
            for key in ("problem", "built", "surfaces", "visual"):
                if not p.get(key):
                    raise PortfolioError(f"flagship {pid!r} needs {key!r}")
            if len(p["built"]) > MAX_BUILT:
                raise PortfolioError(f"flagship {pid!r} lists more than {MAX_BUILT} 'built' items")
        if not isinstance(p["stack"], list) or not isinstance(p["repository_sources"], list):
            raise PortfolioError(f"product {pid!r}: 'stack' and 'repository_sources' must be lists")
        if p.get("publish_name") is False:
            raise PortfolioError(f"product {pid!r} has publish_name=false; remove it instead of listing it")
        for src in p["repository_sources"]:
            if not isinstance(src, dict) or src.get("kind") not in SOURCE_KINDS:
                raise PortfolioError(f"product {pid!r} has an invalid repository source")
            if src["kind"] == "public":
                full = str(src.get("repo", ""))
                if not PUBLIC_REPO_RE.match(full) or full.split("/")[0].lower() != OWNER.lower():
                    raise PortfolioError(f"product {pid!r}: public source must be '{OWNER}/<repo>'")
                if full.split("/")[1].lower() in excluded:
                    raise PortfolioError(f"product {pid!r} references excluded repository {full!r}")
            else:
                label = str(src.get("label", ""))
                if "/" in label or "github.com" in label.lower() or "repo" in src:
                    raise PortfolioError(f"product {pid!r}: a {src['kind']} source must be an opaque label")
        has_public = any(s["kind"] == "public" for s in p["repository_sources"])
        if p.get("publish_repository_links") and not has_public:
            raise PortfolioError(f"product {pid!r} publishes repository links without a public source")
        for link in p.get("public_links") or []:
            url = safe_http_url(str((link or {}).get("url", "")))
            if not url or not str(link.get("label", "")).strip():
                raise PortfolioError(f"product {pid!r} has an invalid public link")
            if is_github_url(url):
                raise PortfolioError(f"product {pid!r}: public_links must not point at github.com; use repository_sources")
        if p.get("collaboration") is not None:
            c = p["collaboration"]
            if not isinstance(c, dict) or not str(c.get("label", "")).strip() or not str(c.get("evidence", "")).strip():
                raise PortfolioError(f"product {pid!r}: collaboration needs 'label' and 'evidence'")
            if has_public:
                raise PortfolioError(f"product {pid!r}: a collaboration cannot claim an owned public repository")
    if flagships > MAX_FLAGSHIPS:
        raise PortfolioError(f"at most {MAX_FLAGSHIPS} flagship products are allowed")
    overrides = data.get("archive_overrides") or {}
    if not isinstance(overrides, dict):
        raise PortfolioError("'archive_overrides' must be an object")
    for name, override in overrides.items():
        if name.startswith("$"):
            continue
        if not isinstance(override, dict) or set(override) - OVERRIDE_ALLOWED:
            raise PortfolioError(f"archive override {name!r} has disallowed field(s)")
        if name.lower() in excluded:
            raise PortfolioError(f"archive override {name!r} targets an excluded repository")
        if override.get("group") and override["group"] not in groups:
            raise PortfolioError(f"archive override {name!r} has unknown group")
    private_entries = (data.get("private_archive_entries") or {}).get("entries") or []
    for i, e in enumerate(private_entries):
        if not isinstance(e, dict) or set(e) - PRIVATE_ARCHIVE_ALLOWED:
            raise PortfolioError(f"private archive entry {i} has disallowed field(s)")
        for key in ("display_name", "summary", "group"):
            if not str(e.get(key, "")).strip():
                raise PortfolioError(f"private archive entry {i} is missing {key!r}")
        if e["group"] not in groups:
            raise PortfolioError(f"private archive entry {i} has unknown group")
        text = " ".join(str(v) for v in e.values()).lower()
        if "github.com" in text or "/" in str(e["display_name"]):
            raise PortfolioError(f"private archive entry {i} must not contain repository references")


def archive_overrides(data: dict) -> dict:
    return {k: v for k, v in (data.get("archive_overrides") or {}).items() if not k.startswith("$")}


def product_from_entry(p: dict, listed_names: set[str]) -> Product:
    public_repos = []
    for src in p["repository_sources"]:
        if src["kind"] == "public":
            full = src["repo"]
            if full.split("/")[1].lower() not in listed_names:
                raise PortfolioError(f"product {p['product_id']!r} references {full!r}, which is not a listed public repository")
            public_repos.append(full)
    return Product(
        product_id=p["product_id"],
        name=p["display_name"],
        tagline=p["tagline"],
        summary=p["summary"],
        role=p["role"],
        status=p["status"],
        access=p["access"],
        category=p["category"],
        stack=[str(s) for s in p["stack"]],
        tier=int(p["featured_tier"]),
        sort_order=int(p["sort_order"]),
        problem=str(p.get("problem") or ""),
        built=[str(b) for b in (p.get("built") or [])],
        surfaces=[str(s) for s in (p.get("surfaces") or [])],
        status_note=str(p.get("status_note") or ""),
        visual=str(p.get("visual") or ""),
        public_repos=public_repos,
        public_links=[{"label": str(l["label"]), "url": safe_http_url(str(l["url"]))} for l in (p.get("public_links") or [])],
        publish_repository_links=bool(p.get("publish_repository_links", False)),
        collaboration=p.get("collaboration"),
    )


# --------------------------------------------------------------------------- assemble

def build(repos: Iterable[dict], portfolio: dict, owner: str = OWNER, profile_repo: str = PROFILE_REPO) -> tuple[list[Product], list[ArchiveEntry]]:
    listed = [r for r in repos if is_listed(r, portfolio, owner, profile_repo)]
    listed_names = {str(r.get("name", "")).lower() for r in listed}
    products = [product_from_entry(p, listed_names) for p in portfolio["products"]]

    claimed: dict[str, str] = {}
    for p in products:
        for full in p.public_repos:
            name = full.split("/")[1].lower()
            if name in claimed:
                raise PortfolioError(f"repository {full!r} is claimed by both {claimed[name]!r} and {p.product_id!r}")
            claimed[name] = p.product_id

    groups = archive_groups(portfolio)
    overrides = archive_overrides(portfolio)
    archive = [archive_entry_from_repo(r, overrides, groups, owner) for r in listed
               if str(r.get("name", "")).lower() not in claimed]
    for e in (portfolio.get("private_archive_entries") or {}).get("entries") or []:
        archive.append(ArchiveEntry(name=e["display_name"], summary=e["summary"], stack=str(e.get("stack") or ""),
                                    group=e["group"], access=str(e.get("access") or "Private")))

    seen: set[str] = set()
    for name in [p.name for p in products] + [a.name for a in archive]:
        key = " ".join(name.lower().split())
        if key in seen:
            raise PortfolioError(f"duplicate project name {name!r}")
        seen.add(key)

    products.sort(key=lambda p: (p.tier, p.sort_order, p.name.lower()))
    order = {g: i for i, g in enumerate(groups)}
    archive.sort(key=lambda a: (order[a.group], a.name.lower()))
    return products, archive


# --------------------------------------------------------------------------- render

def picture(basename: str, alt: str) -> list[str]:
    light = f"{ASSET_PREFIX}/{basename}-light.svg"
    dark = f"{ASSET_PREFIX}/{basename}-dark.svg"
    return [
        "<picture>",
        f'  <source media="(prefers-color-scheme: dark)" srcset="{dark}">',
        f'  <source media="(prefers-color-scheme: light)" srcset="{light}">',
        f'  <img alt="{escape_attr(alt)}" src="{light}" width="100%">',
        "</picture>",
    ]


def escape_attr(text: str) -> str:
    return " ".join(str(text or "").split()).replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")


def _links(p: Product) -> list[str]:
    out = [f"[{escape_md(name)}]({url})" for name, url in p.repo_urls]
    out += [f"[{escape_md(l['label'])}]({l['url']})" for l in p.public_links if l["url"]]
    return out


def render_flagship(p: Product, index: int) -> list[str]:
    alt = f"{p.name} system diagram: {', '.join(p.surfaces)}."
    out = [f"### {escape_md(p.name)}", ""]
    out += picture(f"flagship-{p.visual}", alt) + [""]
    out += [f"**{escape_md(p.tagline)}**", "", escape_md(p.problem), ""]
    out += [f"- {escape_md(b)}" for b in p.built[:MAX_BUILT]] + [""]
    meta = [escape_md(p.role), escape_md(p.status), escape_md(p.access)] + _links(p)
    lines = [
        f"<b>Surfaces</b> {escape_md(' · '.join(p.surfaces))}",
        f"<b>Stack</b> {escape_md(' · '.join(p.stack))}",
        " · ".join(meta),
    ]
    if p.status_note:
        lines.append(f"<i>{escape_md(p.status_note)}</i>")
    # One source line: GitHub turns a line-ending <br> into a double break.
    out += [f"<sub>{'<br>'.join(lines)}</sub>", ""]
    return out


def render_ecosystem_item(p: Product) -> list[str]:
    title = f"**{escape_md(p.name)}**"
    if p.repo_urls:
        title = f"**[{escape_md(p.name)}]({p.repo_urls[0][1]})**"
    meta = [escape_md(' · '.join(p.stack))]
    if p.is_collaboration:
        c = p.collaboration or {}
        meta.append(f"{escape_md(c.get('label', ''))} · {escape_md(p.role)} · {escape_md(c.get('evidence', ''))}")
    else:
        meta.append(escape_md(p.role))
    meta.append(f"{escape_md(p.status)} · {escape_md(p.access)}")
    extra = _links(p)[1:] if p.repo_urls else _links(p)
    if extra:
        meta.append(" · ".join(extra))
    return [f"{title} · {escape_md(p.tagline)}<br>{escape_md(p.summary)}<br><sub>{' &nbsp;·&nbsp; '.join(meta)}</sub>", ""]


def render_portfolio_block(products: list[Product]) -> str:
    out = [PORTFOLIO_START, GENERATED_NOTE, ""]
    flagships = [p for p in products if p.tier == 1]
    ecosystem = [p for p in products if p.tier == 2 and not p.is_collaboration]
    collabs = [p for p in products if p.is_collaboration]

    out += ["## Flagship Product Systems", ""]
    if flagships:
        for i, p in enumerate(flagships, 1):
            out += render_flagship(p, i)
    else:
        out += ["_No flagship products yet._", ""]

    out += ["## Selected Product Ecosystem", "",
            "<sub>Products are grouped by what they do, not by repository: a backend, a client and a website of one product are one entry.</sub>", ""]
    if ecosystem:
        for p in ecosystem:
            out += render_ecosystem_item(p)
    else:
        out += ["_Nothing to show yet._", ""]

    out += ["## Selected Collaborations", "",
            "<sub>Partner-owned products where my commits or pull requests are verifiable. Ownership stays with the partner; no private repositories are linked.</sub>", ""]
    if collabs:
        for p in collabs:
            out += render_ecosystem_item(p)
    else:
        out += ["_Nothing to show yet._", ""]
    out.append(PORTFOLIO_END)
    return "\n".join(out)


def render_archive_row(a: ArchiveEntry) -> str:
    name = cell(a.name)
    title = f"[{name}]({a.url})" if a.url else f"**{name}**"
    subs = [x for x in (escape_md(a.stack), escape_md(a.access)) if x]
    left = title + (f"<br><sub>{' · '.join(subs)}</sub>" if subs else "")
    return f"| {left} | {cell(a.summary)} |"


def render_archive_block(archive: list[ArchiveEntry], groups: tuple[str, ...]) -> str:
    out = [ARCHIVE_START, GENERATED_NOTE, "",
           "## Complete Project Archive", "",
           "<sub>Everything else that is safe to show: public repositories discovered automatically from GitHub, plus allowlisted private work under generic names. Products above are not repeated here.</sub>", ""]
    any_group = False
    for group in groups:
        items = [a for a in archive if a.group == group]
        if not items:
            continue
        any_group = True
        out += ["<details>", f"<summary><b>{escape_attr(group)}</b> ({len(items)})</summary>", "",
                "| Project | What it does |", "| --- | --- |"]
        out += [render_archive_row(a) for a in items]
        out += ["", "</details>", ""]
    if not any_group:
        out += ["_Nothing to show yet._", ""]
    out.append(ARCHIVE_END)
    return "\n".join(out)


# --------------------------------------------------------------------------- output validation

def check_generated_text(text: str, portfolio: dict, listed_public_names: set[str], owner: str = OWNER) -> None:
    """Refuse output that leaks an excluded name or links anything but listed public repositories."""
    low = text.lower()
    for name in excluded_names(portfolio):
        for variant in {name, name.replace("-", " "), name.replace("-", "")}:
            if variant and variant in low:
                raise PortfolioError(f"excluded repository {name!r} would appear in the generated text")
    for url in re.findall(r"https?://[^\s)\"'<>]+", text):
        if is_github_url(url):
            if re.match(rf"^https://github\.com/{re.escape(owner)}/?$", url):
                continue  # the owner's own profile link
            m = re.match(rf"^https://github\.com/{re.escape(owner)}/([A-Za-z0-9_.-]+)/?$", url)
            if not m or m.group(1).lower() not in listed_public_names:
                raise PortfolioError(f"generated text links a GitHub URL that is not a listed public repository: {url}")


def longest_word(text: str) -> int:
    """Longest unbreakable visible word (markup and URLs removed) — a mobile overflow guard."""
    visible = re.sub(r"(?:https?://|mailto:)\S+", "", text)
    visible = re.sub(r"<[^>]+>", " ", visible)
    visible = re.sub(r"[\[\]()|*_`#]", " ", visible)
    return max((len(w) for w in visible.split()), default=0)


# --------------------------------------------------------------------------- README update

def find_block(readme: str, start: str, end: str) -> tuple[int, int]:
    s = readme.find(start)
    e = readme.find(end)
    if s < 0 or e < 0 or e < s:
        raise PortfolioError(f"README markers {start} / {end} not found; refusing to modify the file")
    return s, e + len(end)


def replace_block(readme: str, start: str, end: str, block: str) -> str:
    s, e = find_block(readme, start, end)
    return readme[:s] + block + readme[e:]


def update_readme_text(readme: str, products: list[Product], archive: list[ArchiveEntry], groups: tuple[str, ...]) -> str:
    readme = replace_block(readme, PORTFOLIO_START, PORTFOLIO_END, render_portfolio_block(products))
    readme = replace_block(readme, ARCHIVE_START, ARCHIVE_END, render_archive_block(archive, groups))
    return readme


# --------------------------------------------------------------------------- footprint

def load_footprint(path: str) -> dict:
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data.get("metrics"), list) or not data["metrics"]:
        raise PortfolioError("footprint.json must contain a non-empty 'metrics' list")
    for m in data["metrics"]:
        if not isinstance(m.get("value"), int) or m["value"] < 0 or not m.get("label"):
            raise PortfolioError("every footprint metric needs an integer 'value' and a 'label'")
    return data


# --------------------------------------------------------------------------- main

def _write_if_changed(path: str, content: str) -> bool:
    try:
        with open(path, encoding="utf-8") as fh:
            if fh.read() == content:
                return False
    except OSError:
        pass
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Refresh the generated portfolio blocks in README.md")
    parser.add_argument("--readme", default="README.md")
    parser.add_argument("--portfolio", default=DEFAULT_PORTFOLIO)
    parser.add_argument("--footprint", default=DEFAULT_FOOTPRINT, help="footprint data ('' to skip proof-strip rendering)")
    parser.add_argument("--out-portfolio", default=DEFAULT_OUT_PORTFOLIO, help="also write the portfolio block here ('' to skip)")
    parser.add_argument("--out-archive", default=DEFAULT_OUT_ARCHIVE, help="also write the archive block here ('' to skip)")
    parser.add_argument("--input", help="read repositories from a JSON file instead of the GitHub API (testing)")
    parser.add_argument("--dry-run", action="store_true", help="print the blocks, do not write files")
    args = parser.parse_args(argv)

    try:
        with open(args.readme, encoding="utf-8") as fh:
            readme = fh.read()
        find_block(readme, PORTFOLIO_START, PORTFOLIO_END)  # validate markers before any network work
        find_block(readme, ARCHIVE_START, ARCHIVE_END)
        portfolio = load_portfolio(args.portfolio)
        footprint = load_footprint(args.footprint) if args.footprint else None
        if args.input:
            with open(args.input, encoding="utf-8") as fh:
                repos = json.load(fh)
        else:
            repos = fetch_public_repos()
        if not any(is_listed(r, portfolio) for r in repos):
            raise PortfolioError("the API returned no listable public repositories")
        products, archive = build(repos, portfolio)
        groups = archive_groups(portfolio)
        new_readme = update_readme_text(readme, products, archive, groups)
        listed = {str(r.get("name", "")).lower() for r in repos if is_listed(r, portfolio)}
        check_generated_text(new_readme, portfolio, listed)
    except PortfolioError as exc:
        print(f"portfolio: {exc} — README left unchanged", file=sys.stderr)
        return 1
    except (OSError, json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        print(f"portfolio: {exc.__class__.__name__}: {exc} — README left unchanged", file=sys.stderr)
        return 1

    if args.dry_run:
        print(render_portfolio_block(products))
        print(render_archive_block(archive, groups))
        return 0
    changed = []
    if _write_if_changed(args.readme, new_readme):
        changed.append(args.readme)
    if args.out_portfolio and _write_if_changed(args.out_portfolio, render_portfolio_block(products) + "\n"):
        changed.append(args.out_portfolio)
    if args.out_archive and _write_if_changed(args.out_archive, render_archive_block(archive, groups) + "\n"):
        changed.append(args.out_archive)
    if footprint:
        for theme in ("light", "dark"):
            path = asset_path("proof-strip", theme)
            if _write_if_changed(path, render_proof_strip(footprint, theme)):
                changed.append(path)
    print(f"portfolio: {len(products)} product(s), {len(archive)} archive entr(ies); changed: {', '.join(changed) if changed else 'nothing'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
